spring:
  datasource:
    url: jdbc:mysql://192.168.1.18:3306/mcms-4.7.0?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
    filters: wall,mergeStat
    type: com.alibaba.druid.pool.DruidDataSource