spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/db-mcms-4-6-1?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
    filters: wall,mergeStat
    type: com.alibaba.druid.pool.DruidDataSource