spring:
  datasource:
    url: jdbc:mysql://imingsoft.cn:3307/db-mcms-5.0?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true
    username: mcms
    password: mcms
    filters: wall,mergeStat
    type: com.alibaba.druid.pool.DruidDataSource