#服务配置
server:
  #端口
  port: 8081
  #项目名称
  servlet.context-path: /ms-mcms
  
# slf4j日志配置
logging:
 # 配置级别
 level:
  #分包配置级别，即不同的目录下可以使用不同的级别
  net.mingsoft: trace
#铭飞配置      
ms:
 manager: 
  path: /ms
  view-path: /WEB-INF/manager
 #session配置 
 session: 
  timeout: 1800000 #会话超时， 单位：毫秒， 20m=1200000ms, 30m=1800000ms, 60m=3600000ms
  validation-interval: 120000 #会话清理间隔时间， 单位：毫秒，2m=120000ms
  
 #上传配置
 upload: 
   path: /upload 
   denied: exe
   allowed: jpg
   max-size: 1
   memory-size: 4096
      
#spring配置
spring:
  profiles:
    active: dev
  mvc:
    pathmatch: 
     use-suffix-pattern: true
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: static/**,WEB-INF/**
  servlet:
    multipart:
      max-request-size: 100MB
  freemarker:
    suffix: .ftl
    charset: UTF-8
    content-type: text/html
    allow-request-override: true
    allow-session-override: true
    expose-request-attributes: true
    expose-session-attributes: true
    expose-spring-macro-helpers: true
    prefer-file-system-access: false
    template-loader-path: classpath:/WEB-INF/manager
    settings: 
      template_update_delay: 1
      default_encoding: UTF-8
      classic_compatible: true
      date_format: yyyy-MM-dd
      time_format: HH:mm:ss
      datetime_format: yyyy-MM-dd HH:mm:ss
      auto_import: /include/macro.ftl as ms
      
mybatis:
  mapper-locations: classpath*:**/dao/*.xml
  configuration: 
   database-id: mysql