application: 
 version: mcms-4.7.0
server:
  port: 8080
  servlet.context-path: /ms-mcms
  
logging:
 level:
  net.mingsoft: trace
ms:
 manager: 
  path: /ms
  view-path: /WEB-INF/manager
 session: 
  timeout: 1800000 
  validation-interval: 120000 
  
 upload: 
   path: /upload 
   denied: exe
   allowed: jpg
   max-size: 1
   memory-size: 4096
      
spring:
  profiles:
    active: dev
  mvc:
    pathmatch: 
     use-suffix-pattern: true
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: static/**,WEB-INF/**
  servlet:
    multipart:
      max-request-size: 100MB
  freemarker:
    suffix: .ftl
    charset: UTF-8
    content-type: text/html
    allow-request-override: true
    allow-session-override: true
    expose-request-attributes: true
    expose-session-attributes: true
    expose-spring-macro-helpers: true
    prefer-file-system-access: false
    template-loader-path: classpath:/WEB-INF/manager
    settings: 
      template_update_delay: 1
      default_encoding: UTF-8
      classic_compatible: true
      date_format: yyyy-MM-dd
      time_format: HH:mm:ss
      datetime_format: yyyy-MM-dd HH:mm:ss
      auto_import: /include/macro.ftl as ms
      
mybatis:
  mapper-locations: classpath*:**/dao/*.xml
  configuration: 
   database-id: mysql