spring:
  datasource:
    url: jdbc:mysql://imingsoft.cn:3307/db-mcms-open?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true
    username: root
    password: root@78
    filters: wall,mergeStat
    type: com.alibaba.druid.pool.DruidDataSource