server:
  port: 8081
  tomcat:
    max-http-header-size: 10240     #单位：字节
spring:
  profiles:
    active: dev
  mvc:
    pathmatch: 
     use-suffix-pattern: true
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: static/**,WEB-INF/**
  servlet:
    multipart:
      max-request-size: 100MB
  freemarker:
    allow-request-override: false
    allow-session-override: false
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    enabled: true
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: true
    prefer-file-system-access: true
    suffix: .ftl
    template-loader-path: classpath:/WEB-INF/manager/
    settings: 
      template_update_delay: 0
      default_encoding: UTF-8
      classic_compatible: true
      date_format: yyyy-MM-dd
      time_format: HH:mm:ss
      datetime_format: yyyy-MM-dd HH:mm:ss
      auto_import: /include/macro.ftl as ms
      
mybatis:
  mapper-locations: classpath*:**/dao/*.xml
  configuration: 
   database-id: mysql

# slf4j日志配置
logging:
 # 配置级别
 level:
  #分包配置级别，即不同的目录下可以使用不同的级别
  net.mingsoft: trace
  com.mingsoft: trace
      
ms:
 manager: 
  path: /ms
  view:  #已过期
   path:  
 session: 
  timeout: 1800000 #会话超时， 单位：毫秒， 20m=1200000ms, 30m=1800000ms, 60m=3600000ms
  validation.interval: 120000 #会话清理间隔时间， 单位：毫秒，2m=120000ms
 upload: 
   path: /upload 
   denied: exe
   allowed: jpg
   max:
    size: 1
   memory:
    size: 4096